"""
FastAPI backend for the RAG Chatbot.

Exposes:
  POST /api/chat      - query the RAG system
  GET  /api/stats     - knowledge base statistics
  POST /api/reindex   - re-index documents from data/ folder
  GET  /api/health    - health check

Static files are served from ./frontend/ at the root path.

Run with:
    uvicorn server:app --reload --port 8000
"""

import logging
import sys
import asyncio
from pathlib import Path

# ── ensure project root is on the path ────────────────────────────────────────
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

# ── logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# ── FastAPI imports ───────────────────────────────────────────────────────────
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="RAG Chatbot API",
    description="FastAPI backend for the RAG document assistant",
    version="1.0.0",
)

# Allow all origins so the standalone HTML file can call the API when opened
# directly from disk during development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Shared RAG chain (lazy-loaded on first request) ───────────────────────────
_rag_chain = None


def get_rag_chain():
    """Return the singleton RAGChain, initialising it if necessary."""
    global _rag_chain
    if _rag_chain is None:
        logger.info("Initialising RAG chain…")
        from generation.rag_chain import RAGChain
        from utils.config import Config

        if not Config.validate():
            raise RuntimeError(
                "Configuration invalid – please set GROQ_API_KEY in your .env file."
            )
        _rag_chain = RAGChain()
        logger.info("RAG chain ready.")
    return _rag_chain


# ── Request / Response schemas ────────────────────────────────────────────────

class ChatRequest(BaseModel):
    query: str = Field(..., min_length=1, description="User question")
    top_k: int = Field(4, ge=1, le=10, description="Number of documents to retrieve")
    temperature: float = Field(0.7, ge=0.0, le=1.0, description="LLM temperature")
    provider: Optional[str] = Field(None, description="LLM provider: 'groq' or 'gemini'")
    model: Optional[str] = Field(None, description="Model name override within the provider")


class SourceItem(BaseModel):
    source: str
    content: str


class ChatResponse(BaseModel):
    answer: str
    query: str
    sources: list[SourceItem] = []
    insufficient_info: bool = False
    error: Optional[str] = None
    provider: Optional[str] = None
    model: Optional[str] = None


class StatsResponse(BaseModel):
    vector_store: dict = {}
    retriever: dict = {}
    llm: dict = {}
    chunk_size: int = 0
    chunk_overlap: int = 0
    top_k: int = 0


class ReindexResponse(BaseModel):
    success: bool
    message: str
    doc_count: int = 0
    chunk_count: int = 0


class SyncResponse(BaseModel):
    success: bool
    message: str
    removed_sources: list[str] = []
    deleted_chunks: int = 0
    kept_sources: list[str] = []


# ── Cached suggestions (regenerated on reindex / restart) ─────────────────────
_cached_suggestions: list[str] | None = None


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {"status": "ok"}


@app.get("/api/providers")
async def providers():
    """Return all available LLM providers and their models."""
    from generation.llm_factory import list_providers
    from utils.config import Config
    catalogue = list_providers()
    return {
        "providers": catalogue,
        "active_provider": Config.LLM_PROVIDER,
    }


@app.get("/api/suggestions")
async def suggestions():
    """Return topic-specific question suggestions generated by the LLM."""
    global _cached_suggestions
    import random

    # Return cached suggestions if available
    if _cached_suggestions:
        return {"suggestions": _cached_suggestions}

    try:
        chain = get_rag_chain()
        collection = chain.vector_store.vector_store._collection
        total = collection.count()

        if total == 0:
            return {"suggestions": []}

        # Grab a random sample of chunks to show the LLM what the docs are about
        sample_size = min(total, 15)
        all_data = collection.get(include=["documents"])
        docs = all_data.get("documents", [])

        indices = random.sample(range(len(docs)), min(sample_size, len(docs)))
        sampled_texts = [docs[i][:300] for i in indices]  # first 300 chars each
        combined_sample = "\n---\n".join(sampled_texts)

        # Ask the LLM to generate topic-specific questions
        prompt = (
            "You are given random excerpts from a knowledge base. "
            "Based ONLY on the topics, people, places, and concepts you see in "
            "these excerpts, generate exactly 4 short, specific, and interesting "
            "questions that a user might ask about this content.\n\n"
            "Rules:\n"
            "- Each question must be specific to the actual content (mention real "
            "names, places, concepts, or terms from the excerpts)\n"
            "- Keep each question under 50 characters if possible\n"
            "- Return ONLY the 4 questions, one per line, numbered 1-4\n"
            "- Do NOT add any other text, explanation, or formatting\n\n"
            f"Excerpts:\n{combined_sample}\n\n"
            "Questions:"
        )

        response = chain.llm.generate_response(prompt)

        # Parse the 4 questions from the response
        lines = [
            line.strip().lstrip("0123456789.)- ").strip()
            for line in response.strip().split("\n")
            if line.strip()
        ]
        questions = [q for q in lines if len(q) > 5 and q.endswith("?")][:4]

        if len(questions) >= 2:
            _cached_suggestions = questions
            return {"suggestions": questions}

        # Fallback if LLM parsing failed
        return {"suggestions": []}

    except Exception as e:
        logger.warning(f"Suggestions error: {e}")
        return {"suggestions": []}


@app.post("/api/reindex_suggestions")
async def reindex_suggestions():
    """Clear cached suggestions so they regenerate on next load."""
    global _cached_suggestions
    _cached_suggestions = None
    return {"success": True, "message": "Suggestion cache cleared"}


@app.post("/api/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    """Run a user query through the RAG pipeline and return the answer."""
    try:
        chain = get_rag_chain()
        result = chain.chat(
            query=req.query,
            k=req.top_k,
            provider=req.provider,
            llm_model=req.model,
        )
        return ChatResponse(
            answer=result.get("answer", ""),
            query=result.get("query", req.query),
            sources=[
                SourceItem(source=s.get("source", ""), content=s.get("content", ""))
                for s in result.get("sources", [])
            ],
            insufficient_info=result.get("insufficient_info", False),
            error=result.get("error"),
            provider=result.get("provider"),
            model=result.get("model"),
        )
    except RuntimeError as e:
        # Configuration / init errors – return a helpful 503
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        logger.error(f"Chat error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/stats", response_model=StatsResponse)
async def stats():
    """Return knowledge base and system statistics."""
    try:
        chain = get_rag_chain()
        s = chain.get_system_stats()
        return StatsResponse(**s)
    except Exception as e:
        logger.warning(f"Stats error: {e}")
        return StatsResponse()


@app.post("/api/reindex", response_model=ReindexResponse)
async def reindex():
    """Re-index all documents from the data/ folder."""
    try:
        chain = get_rag_chain()
        from ingestion.document_loader import DocumentLoader
        from ingestion.text_splitter import TextSplitter

        loader = DocumentLoader()
        docs = loader.load_all_documents()
        if not docs:
            return ReindexResponse(
                success=False,
                message="No documents found in data/ folder.",
            )
        splitter = TextSplitter()
        chunks = splitter.split_documents(docs)
        chain.vector_store.add_documents(chunks)
        # Clear suggestion cache so they regenerate from new content
        global _cached_suggestions
        _cached_suggestions = None
        return ReindexResponse(
            success=True,
            message=f"Indexed {len(chunks)} chunks from {len(docs)} documents.",
            doc_count=len(docs),
            chunk_count=len(chunks),
        )
    except Exception as e:
        logger.error(f"Reindex error: {e}")
        return ReindexResponse(success=False, message=str(e))


@app.post("/api/sync", response_model=SyncResponse)
async def sync():
    """Remove chunks from the vector store whose source documents no longer exist on disk."""
    try:
        chain = get_rag_chain()
        result = chain.vector_store.sync_with_disk()
        removed = result["removed_sources"]
        deleted = result["deleted_chunks"]
        kept    = result["kept_sources"]
        if removed:
            msg = f"Removed {deleted} chunk(s) from {len(removed)} deleted file(s). {len(kept)} file(s) still present."
        else:
            msg = f"All {len(kept)} source file(s) still present. Nothing to remove."
        return SyncResponse(
            success=True,
            message=msg,
            removed_sources=removed,
            deleted_chunks=deleted,
            kept_sources=kept,
        )
    except Exception as e:
        logger.error(f"Sync error: {e}")
        return SyncResponse(success=False, message=str(e))


# ── Startup: schedule indexing in background so port binds immediately ────────

async def _index_documents():
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, get_rag_chain)
        logger.info("Background indexing complete.")
    except Exception as e:
        logger.error(f"Background indexing failed: {e}")


@app.on_event("startup")
async def startup_event():
    """Fire-and-forget: index documents in background, don't block port binding."""
    asyncio.create_task(_index_documents())


# ── Static files (served last so API routes take priority) ────────────────────
frontend_dir = project_root / "frontend"
frontend_dir.mkdir(exist_ok=True)

app.mount("/", StaticFiles(directory=str(frontend_dir), html=True), name="frontend")
